# Generated by Django 4.2.25 on 2025-11-05 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0004_comment_parent"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="parent",
        ),
        migrations.AddField(
            model_name="comment",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
