# Generated by Django 4.2.25 on 2025-11-10 15:17

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0006_alter_comment_options_alter_post_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="content",
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name="Content"),
        ),
    ]
